services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    links:
      - redis
    restart: unless-stopped
    command: gunicorn main:app --bind=0.0.0.0:8000 --workers 1 --worker-class uvicorn.workers.UvicornWorker


  redis:
    container_name: redis
    image: redis:7.4.0-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - ./redis:/data
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}